create_user_records_job:
  cron: "* * * * *"
  class: "CreateUserRecordsJob"
  queue: default
  
update_daily_user_records_stats_job:
  cron: "* * * * *"
  class: "UpdateDailyUserRecordsStatsJob"
  queue: default

test_job:
  cron: "* * * * *"
  class: "TestJob"
  queue: default

