create_user_records_job:
  cron: "5 */1 * * *"
  class: "CreateUserRecordsJob"
  queue: default
  
update_daily_user_records_stats_job:
  cron: "45 23 * * *"
  class: "UpdateDailyUserRecordsStatsJob"
  queue: default

test_job:
  cron: "* * * * *"
  class: "TestJob"
  queue: default

